// var removeDuplicates = function (s) {
//   // 使用栈作为容器
//   const stack = []
//   for (let i of s) {
//     const temp = stack.pop()
//     if (temp !== i) {
//       // 如果栈顶元素不等于当前元素，那么将其加入栈中
//       temp && stack.push(temp)
//       stack.push(i)
//     }
//     console.log(stack)
//   }
//   return stack.join('')
// }

var removeDuplicates = function (s) {
  // 使用栈作为容器
  const stack = []
  for (let i of s) {
    const temp = stack.pop()
    if (temp !== i) {
      // 如果栈顶元素不等于当前元素，那么将其加入栈中
      temp && stack.push(temp)
      stack.push(i)
    }
    // console.log(stack)
  }
  return stack.join('')

  // // 使用双指针
  // const arr = s.split("");
  // let slow = 0;

  // for(let fast = 0; fast < arr.length; fast++) {
  //     arr[slow] = arr[fast]; // 先将字符赋值给慢指针
  //     // if(arr[slow] != arr[fast]) {
  //     //     slow++;
  //     // }
  //     if(slow > 0 && arr[slow] == arr[slow - 1]) {
  //         slow--;
  //     }else {
  //         slow++;
  //     }
  // }
  // return arr.slice(0, slow).join("")
}

console.log(
  removeDuplicates(
    'cjpgjsomosejmrphpsirmhrhestdcigpbpfkhrgptjelkjrqqogcoabkntfdodoegtgbeidsonksnaegofrqndhlepfnjnjbfoqmhbecjsmnjqijplarpjetttcdmaeeottljcgskjigtcocalctttdqtslpjdglqqnndqicjsehblbqicqdjlfqpbfgoslrtjjakacttignfjklqpofjdjoeqficrmljhdkjrbqeimecceamgemljapkcbejeqhqgkeqoajenmdeehstjlbqpqcjtgallepbnajtbegcitpprebcbaqoimpiiigqkhppeltkeempqfamtcnbjgrhpkgtbpdfrnrtaambbeohocsfaohtleqoosemrdliallfnifjdnqjbjbekdcnhgediairamjdhaaegrgejchsoaaetootohslmfoodnkjonefiigqjicnjkqjbniqdjcqmacrcagcfbiqsjlagcjtjordchcflkaelkniehboibdamtpmeiqqospkbnpgktirjgopoetsmqjoiqtflheermfpgjmchmfjgbkapnhqhotjqplrhgmkcjraihdksrelgshfetcostililosmcqternhjkcoaortjbpcnselcnegfcfhfsncleghmkmjblacdtrnqkrpbrpgsoemqhbeiktajigqqqmselcqetqomjoqmmdnapgrtdcgqlccofsnmgatdjdaaaamgeckgrmihpjsbidrcfooptfprqeklpfkrkqpepnpjsjkabrkjkqnnojethaohbnnrgsrhfplmtjqnjnikoeggqogrikkolrsbaethdktrqhlaogfcprfomkqcjqngemekesmqsifipbtneqsapipfpmpslepbqsjlkedknprpraiahatrhrodejtlldjneekarnjjngnfkidnamdrhqinhdpshjrqpncsdolcnfhatngipkskteenniebqjnecntrgtchsrdmgsdbocotttsifebmorpqmfcmqemjlnhcpbbiacjctpctmftkntjmrpkmpitranbcmaqssqapgabinrcaeigpcjiqeqkncbfhalibgdseginqnlccjhstshijdafsagnfhaboqmigfneeddkodocdnhgdiiiftpdrijpoojslffrspkgdfhqlqdnbtqimkqddjpphdmphejqaotmhndodpkjptlpnfctsmkekabrfpifelgckjsplfbaggkhgrebtkksqdsnskbqismrfghpssoqfprlrbkfrtsrdqfoffpkcqeiamqckdlbjnitrsjqrtqjbnrsladreqcaopdqkpijocotrhlgosokqnljtljlrdsbttrkkgtshqeihqstfmqrsrjrcknteqnsqijkprsinaoescbkrnabrdrmlbgblarijkfcptqftsqrfafetnerpttshdngbcjlratfdfnhroogolfqhpopdibnggsqssgcfeaphcksfqtdikniqfipmcbhdqfnkbokeiqepssemmaaprjbkrktqosessnpisitdcpbpsflbsjjpjggcboacpanaeqmkbaibimqicahbbkpqnljelclsfmkbgmdlhpotlahqmogtpoargqhdqtpdnrpmicatqanqtlrmkprjklkehcllafidklpnsbqchpajejcjeppdhlaibassdmcjbtdkipraemmbofgbnpskhgkjdoqffhjbjlhescbrlafnjrbfbspnmkelnijgohkptognttpjfosjnlqcficjdjpdmtqrfillcjbfjsliggaqnigkajsginnthcrnmsgfgkdtcsbsbjdktpohtgmddimmgnslnmsnqtsqqjjdgssejostaklamslggqntgmldhphafbeafjccrpfaojaccncrsqdhnijlihrfsdellgstntijpqdjhdrbhqtslbifrrcspsprikpicknrpsaabnnlmrkkigbbneljmqqchabaipocctciodercbmpmjdhcipsfddhqmmehdgtrigiqfqqecmklefiighooeegalttlpitatdnqkhfctdhrafktjtbohmekalsqmcqrskschhcfjrfsrgkmjtcdmrcollmrjqntnhmkamimgjancrapccfpcjoriaoqnqolgjomniaaeinirablfammopsomsldleophbfakmqqpbqnandantiimhmokqimqgpdhlnckbkenoigedmsontmanoikinfmmmghdfsscqfmjgbenkcrljifrgbipbdobrabenhotacpcrpcgcefenarqcenaiomnkflskpgiratckmepndgrmqkarberpsaflcrlmijrgksbmilrntmcnmbtsrgpcpppapbrotaofmchehpnqreoberedlrfejajbhjmqetabpphfbdjrarkmdepdllqrarrskqkapsfrkdsebrhlqtgftijjclihiqjljsbpmfltgqpbbdkeshrackmlaoitmoibdinlhtnokbqteoskbpaocjkihhfqsdpsibmeajdgsdoorkaloghgrtbanclhitalfjmrhlkttaatjokginrfqsphopfldnnqfjbtejaiakikqhodiklttttfjlqntgqsfimnsstpojlopjlcadehkgnkkjameotdmobilmctmhetembottcsjtgbgbmkcnbqtlqenfjipcmtimqfchlpqjqmqtbdbskgfqmibkqocjdlciesarpttgntnioibhtpcismtgpnbengmnbboelrriqqqhnqockjphkntlgrrmjnndqkgidgihjmjqimmlbgpbtlnlohjmhlesmflklfcrqhbepmceticlcfrhsjrqnbpgqosjkdfqbfpcddnmqjjakllgjmgjjcakpfgfrhpffcagakkoitqiaglsfatjiirlsgaddcjekolioehllqjmagqfgbjojhinkbhjrlpfgoqnmfjofstlkkqesilmrekqqoprhdjmeeaqddardadrjtrtopobmctlkorpjcdaqjljopekajldjeqkttnpfkhtghabkpjkosdbkmrkalcdecoqmbirrmcmtsbntoospfogplhntjbtiqjcjpamqppcfdpcdqqdrhehbljprkhdslsmsomhndarepsndbjlsnantsnhkabrjgrgdhjobohmjmlmdidarjsgoisdpgohgscmnqgfeboqkhfbckqhsjtjrkdfkmoefdmnottjfgljnfrejgnhrlcgfhrfroonjqbkegjmnnihbqoteagogbdfkmebhmsehratsdtfpjtfsgiegktkcflttrnlicidphaqejorntreajegmniaprbtbnsrnagsicsmghboqkkeidjkoqfatisbmeeiasalqbhqrdeltlkrqciktfcsbbfkmtgttebmmefjheeiisqtgaeimaonjclrmssfrkfekqbicrmserkbfpbmncdkqstkiedfoqmhgjtafintdldarneancdjaffkssmeckqsmolpiicsikgagbfkbfmotccdqdlorbcehejgdjpaqgrjmkgfnlabptjpcqkotlebmoqnghrtgeokiknjmhqbspdgcqgcbrjsdjsakfhcpmkbrmctlnidhstgcimaopgktefhbjcntbjmkqescsedoirfcdofbconjmdfbsnmjihmbslomkefmbcktgbfmqjhrbctrafilaamrbiioeiitjbsnnjplomngjafjpfmgbeclhktprafbqsmedfqibpsjdpgrpnfbnhqrtjlnelingkilmdbetqonnamomgjkbiprjkacohjdpfclnglaocfattnsltosqbdnrftgkomhdgsisfjlqkmtsqchsalqpnlhhaksbrqjobrrsgrftconsshiccbfnpesdsaokrsgnlsprhjcfrhqcdtrlmpjaahcfqggoqoiclormbtkmqirdgtkbdflaijericrfhirgjabtedglcelmcdprgtiolroefharklifcqqrmdijilegfdrnskenkfkaabcrfmnmfgjtrfoirgnmjdtogjcckthoenqpptifhkselotdrtrplcmjsetjgbbcccohseoftfebkgdbjqoctgcqllhbfpqnfqdsjprffssjoncqirrknjrqmdrsttmrnheaptlhgsjbosjhdijgfphsshkgppcdlijeonlbnpfaqlgknddhlkbeihkcheeeokcdmjrrtdclkohjcrliliaakqiebkmgpjomspbnpjlcrldqppqgiopennbicnforcnamttdkonmgqotdtpfairoqoibgnlbmmnooimrhfhbdhektlqmbgnnedhqnfkfrtepehcjkcgsnbrjslgtjdimifaqdgtqalcgcqlbafodesneafcpcftbqptgieaqhbrqakkmmlopmsrpctmanghdjrroaktpqehmbllostddmrecmapnooobgmkptslqhqeptntsdnrocosjmmqhjlsnelcrqseohocrmnmstrpemstqaapfspsogkmrbdohiqhnspebmqcpmjdhappifesiqbngeqbchrhhpgjlnrceissglfbdkdtklnqntdcgtgmmearadrksklrsftnheplkljgcicljijpmfptlmohdekdflasdfdihcndqqkgsdndkkapodojtpeqeembmdgrjogpadpkbpogopokifqllhniiqlcbajrqlornbbpgnebgmdcjbbskemppasqdkqteelrpchfrqmmpbjffepkrconkhaesgkqfjfressnbfbcpfnoifekmilpkcfnnifnploljmkjmlhqkctntmatoedpriramidlcjemfgppbcprtksgegfalecdncrfegfflthlfsacepqthcinqonhaspcmtqifklcakjfmghkfjcpclhttnhffileatcqklemscegeiopfekaodegnkmbrdcrqtqkatcdjjpjnrkcsnkqghoegssfbhacdcfrcbtnnfohebkrreqmmhpqdlpkinnnpbrcaqlhhckmiqeggiqlqtrcoitpgdmmppfbefacnhchsgomnficlsnsekqcrjkskapchejbeqsjcprkklcnfgtnodqihrltcrjaeojarocgphbtglnergonshgmqkptkjphjnbhsahrobrmhfgkdjimgnkqbdjlsfhjskesrdiholpgsddpbidnqjjfnscrcalimqikqoketljoqekfqimqomscnbchrkkncnhbbblholahtfhckdpbofjmaobibibtfqsfsrnjtjpnbeedpstqoedlldtajjkpjijbjnlcfciaanhlkrnsagdtkfttjsdjnhenessbbonqjtthmignckbhmmcfjsimnphjndilordjjgbtalthdjfpreahfbdrcnbgpmthnlsqdclsdghdkciflnbpnikeakhsnkdkcqsaofdfnmqbnobtloqlrgmacqrlnmkmapoeimbmrdintembpbdgcincfmkmgdkjtsdstntspbfilejndfmignggagmfisseqtjsnplmmadedtnrcniboogtijngtrogseeonpaktkidgetrfkcokbnoahgdkrtggplthigdjeoimipdtrijknihjdcrpsijejqcgsgikkshfggfjaaettkrkehkbcflhhjcectmjmeersdlcahkpclbealemldeehktaqjndceeerkptrqldplkcrhcmbrhksfbkojblinjcothmlrtqetcfilibddfklaqskcagjjjtotdmcicaqclnrpkdjjnpejiqeepltkhtmfmlrkrfierfrsfcimabigkihtcsrqhgansogdpfpjjrondsdtogkhfohqrbobnqternmhtgoopkaasigssiqkrgbjhghpjjijmlsnhgikpmrlnoonnpmfsaajrrrlmfqeiefcglffioarmrpbdamriajjodkbebobjrskblkqleqetfhfhkkslcdtlptfthcbcodboeokdihkggicggpaegckaoqsqejtmsfltnntjppegfosaltkjqtcbabklbshggalsbaartojseipaccbiafabifdmicojjmofkhdgaotfmcmdpanatbdbkocekiljmealtnskgembgrobracbdctmhhgrmqocgsrjiofotmjfaidfneeariehdpfrqhhdanenmcgjgocgaajmcoolcahorlrtmfpikacenodnbcksqeqcainainlajqhhsmrldmphoolhqqohgakkfefbeaqkbaobaorclgdfprlcmdlimnrbktomhapekqqfidmclqccmdbtentemgepbkpihnpflitaegikshdorjdgfeksaqitklskoqesnqaakhtdnptrkcbshgchgcesnljicagdledtqhfjaqkmlsrafffqrqadqkeinssptlqijjqtscmsmgnqakmkileaglbmjjpdbdcdmnccarmsfbqjdjphroqgneosefbpgdkipqosraqssmcaggrjtcjebqqbbtjsfkqibkrkkrojdgqjtnedscgaholjdknbhnqngfodossabdnpdosrocqldittilqeijgjkeffkjgbkmjdrjmikhraqaerdjhcterdmekpnqajlnbrorfsqjpfkhrfajiqalopkdsgeioreeieridfpckpkjpbocggakfnlrmgcjkacpgjmmqtleqnmcsdhebtpnnkhemgateclkhppsjoelprtgnpgeraaaqassodrokhmmmddlkggcsqabgptfliekirqtdfogkqcjindndrbbbrchpashkncncqnkcdddnttspjijpibnnrotfldtobptcbbdlgpedcjknsoldicnbqtdatsbiqocienlpcghaqsrdreldpnfnrgclhthpleatndsjsnktjaeifkndtiogfstefsdhgagqjicjpikjfbtqqoaktmqgemdfftbfnhrpkaftacigqtjmlfokqffhfhsprkqtdiheslhmoeggofstrfnbqdhjnqabodatfifgmkkdrrrbmkcbegteihkcqtrnncorchgcqlfijobonecpbhccrljejprbjebtpqmaotjqfkkofssdpftjgqqljaqsolgpidsqllqrgctjilalddsllpenmdgiaiieqflsffsklfcdsfdtjshrekqebapktldhqofbopcebigphpabjcslfhbhfokkqbesirsojpajecogmfnhcrlelqccerfcjeoeeharsgfipqiqplgaigkoqdpsbdgdencgtlborreneconcjfjrldlccnfrfoiarhjbgsekdriitjjalbqhanqqddsacnpfkfcqppngtfckhflnrpdlccakekkbthghkrmkpehtlagqtsegtfkifinetbpblqsddsqdfbltrimthqabbdldmijppemdtehplnafoninpdrccthqlqeepcjbpqfnkhenrrogbkirqnmoahioraeomhjebepmobdqepccdlbhejnlktmctatkmrilebehljgiofcpedmeshbeafddbpcineqkmspicrobrcehphjoiegkfhjgtreddohrierelhdpthtgiallfpdnodgmgpjqfssagbqkrjetdcpcqidsjrnashjkeikgqenerqpaingljhrbligdmfnecidksbstahphfoghnmjfirepamroshejooecibrjpnnlknboqgrqgqmntqpmhanoafijhbdaaattifbpaloecfchjqdldtjihndlrenjrfnppjfhshlgiprrgdabkrpkfoericsekmllpfobjfjqatronhlninlcsqeboesbejaimokokhimgdgdtcalfpbctcpbeffdpanespdkiaaikondtoctnagcignmprqtobcjriaampnoikaeofcbipipmkbkgnsqnmhcogkfnkcbepcdeibccbcnheqpmftebfmphfajidingbetdhbqifjehccpptaqclqirdsmitptgnmsctcjqdtpbfdprbihpaqbmdibkolrqhjnhbgqtmdtdjkjipdlbcedrchakqtrjfppcatjflrtbknlpag'
  )
)


